# Generated by Django 3.2.12 on 2022-03-01 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('efne', '0006_auto_20220221_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='efne_attachments', to=settings.AUTH_USER_MODEL),
        ),
    ]
