# Generated by Django 3.2.12 on 2022-05-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efne', '0007_attachment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='fne',
            name='keywords',
            field=models.CharField(blank=True, help_text='Eléments complémentaires pour aider à la catégorisation de la fiche. Renseignés par les utilisateurs analysant la fiche', max_length=250, null=True, verbose_name='Mots-clés'),
        ),
    ]
