# Generated by Django 3.2.12 on 2022-05-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efne', '0008_fne_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fne',
            name='photo',
        ),
        migrations.DeleteModel(
            name='SubAttachment',
        ),
    ]
