# Generated by Django 3.2.13 on 2022-07-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efne', '0009_auto_20220519_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='fneaction',
            name='is_complete',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Complète'),
        ),
    ]
