# Generated by Django 3.2.13 on 2022-10-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efne', '0011_auto_20221004_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('rank', 'label'), 'verbose_name': 'Rôle', 'verbose_name_plural': 'Rôles'},
        ),
        migrations.AddField(
            model_name='role',
            name='rank',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
    ]
