# Generated by Django 3.2.13 on 2022-10-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0010_safetycuberef'),
        ('efne', '0013_fne_safetycube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fne',
            name='event_date',
            field=models.DateTimeField(verbose_name="Date de l'évènement"),
        ),
        migrations.AlterField(
            model_name='fne',
            name='position',
            field=models.CharField(max_length=25, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='fne',
            name='regroupement',
            field=models.CharField(max_length=25, verbose_name='Regroupement'),
        ),
        migrations.AlterField(
            model_name='fne',
            name='safetycube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_efne', to='shared.safetycuberef', verbose_name='Référence SafetyCube'),
        ),
        migrations.AlterField(
            model_name='fne',
            name='secteur',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Secteur'),
        ),
    ]
