# Generated by Django 3.2.7 on 2021-10-23 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shared', '0002_userdetail_be_notified_on_simi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('assigned_to_person', models.CharField(blank=True, max_length=25, null=True, verbose_name='Responsable')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('should_notify', models.BooleanField(default=False, verbose_name='Devrait déclencher un notification')),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'évènement")),
                ('with_incident', models.BooleanField(default=False, verbose_name='Avec incident')),
                ('description', models.TextField(verbose_name='Description du problème rencontré')),
                ('assigned_to_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similitude', to='auth.group', verbose_name='Attribué à')),
            ],
            options={
                'verbose_name': 'Formulaire',
                'verbose_name_plural': 'Formulaires',
                'ordering': ['event_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimiCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Catégorie')),
                ('date', models.DateField(verbose_name="Date d'enregistrement")),
                ('id_list_as_string', models.TextField(help_text='Liste des identifiants uniques de fiche séparées par des points-virgules', verbose_name='Liste des fiches')),
            ],
            options={
                'verbose_name': 'Compteur',
                'verbose_name_plural': 'Statistiques',
            },
        ),
        migrations.CreateModel(
            name='SubData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inca_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Numéro INCA')),
                ('parent_simi', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sub_data', to='similitude.simi', verbose_name='Fiche parente')),
            ],
            options={
                'verbose_name': 'Données sub',
            },
        ),
        migrations.CreateModel(
            name='SimiAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Action', max_length=250, verbose_name='Intitulé')),
                ('is_default', models.BooleanField(default=False, verbose_name='Par défaut')),
                ('is_terminal', models.BooleanField(default=False, verbose_name='Terminale')),
                ('current_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similitude_graph_for_current_group', to='auth.group', verbose_name='Responsable actuel')),
                ('current_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similitude_graph_for_current', to='shared.status', verbose_name='Statut actuel')),
                ('next_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similitude_graph_for_next_group', to='auth.group', verbose_name='Prochain responsable')),
                ('next_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similitude_graph_for_next', to='shared.status', verbose_name='Prochain statut')),
            ],
            options={
                'verbose_name': 'Action possible',
                'verbose_name_plural': "Graphe d'actions",
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='simi',
            name='available_actions',
            field=models.ManyToManyField(blank=True, default=None, editable=False, to='similitude.SimiAction', verbose_name='Actions possibles'),
        ),
        migrations.AddField(
            model_name='simi',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similitude', to='shared.status', verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='Redactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('simi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redactors', to='similitude.simi')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similitude_redactors', to='shared.team')),
            ],
            options={
                'verbose_name': 'Rédacteur',
                'verbose_name_plural': 'Rédacteurs',
            },
        ),
        migrations.CreateModel(
            name='PostIt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similitude_postits', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postits', to='similitude.subdata')),
            ],
            options={
                'verbose_name': 'Post-it',
                'verbose_name_plural': 'Post-its',
                'ordering': ['creation_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=100, verbose_name='Indicatif')),
                ('strip', models.FileField(blank=True, max_length=250, null=True, upload_to='simi/%Y/%m/strips/', verbose_name='Photo du strip')),
                ('type', models.CharField(blank=True, max_length=4, null=True, verbose_name='Type')),
                ('provenance', models.CharField(blank=True, max_length=4, null=True, verbose_name='Provenance')),
                ('destination', models.CharField(blank=True, max_length=4, null=True, verbose_name='Destination')),
                ('position', models.CharField(blank=True, max_length=250, null=True, verbose_name='Position')),
                ('ssr', models.CharField(blank=True, default='', max_length=20, verbose_name='Code SSR')),
                ('fl', models.PositiveIntegerField(null=True, verbose_name='Niveau')),
                ('simi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrafts', to='similitude.simi')),
            ],
            options={
                'verbose_name': 'Aéronef',
                'verbose_name_plural': 'Aéronefs',
            },
        ),
    ]
