# Generated by Django 3.2.7 on 2021-12-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('similitude', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simicounter',
            options={'ordering': ('-date', 'category'), 'verbose_name': 'Compteur', 'verbose_name_plural': 'Statistiques'},
        ),
    ]
