# Generated by Django 3.2.13 on 2022-10-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similitude', '0004_simiaction_is_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simiaction',
            options={'ordering': ['rank', 'is_default', 'next_status__label', 'next_group__name'], 'verbose_name': 'Action possible', 'verbose_name_plural': "Graphe d'actions"},
        ),
        migrations.AddField(
            model_name='simiaction',
            name='rank',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
    ]
