# Generated by Django 3.2.13 on 2022-10-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0010_safetycuberef'),
        ('similitude', '0006_simi_safetycube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simi',
            name='event_date',
            field=models.DateTimeField(verbose_name="Date de l'évènement"),
        ),
        migrations.AlterField(
            model_name='simi',
            name='safetycube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_similitude', to='shared.safetycuberef', verbose_name='Référence SafetyCube'),
        ),
    ]
