# Generated by Django 3.2.7 on 2021-10-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='be_notified_on_simi',
            field=models.BooleanField(default=False, verbose_name="Notification Similitude d'Indicatifs"),
        ),
    ]
