# Generated by Django 3.2.7 on 2021-11-05 09:57

from django.db import migrations

# permissions are created during post_migrate


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_adds_notification_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupdetail',
            options={'permissions': (('validator', 'Valide les formulaire'), (
                'investigator', 'Analyse les formulaires'), ('all_access', 'A accès à tous les formulaires'))},
        ),
        migrations.RemoveField(
            model_name='groupdetail',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupdetail',
            name='has_all_access',
        ),
        migrations.RemoveField(
            model_name='groupdetail',
            name='is_investigator',
        ),
        migrations.RemoveField(
            model_name='groupdetail',
            name='is_validator',
        ),
    ]
