# Generated by Django 3.2.12 on 2022-05-16 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_alter_userdetail_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=2, unique=True, verbose_name='Identifiant')),
                ('color', models.CharField(blank=True, help_text='ex : #', max_length=10, null=True, verbose_name='Couleur')),
            ],
            options={
                'verbose_name': 'Zone',
                'ordering': ('short_name',),
            },
        ),
        migrations.RemoveField(
            model_name='team',
            name='category',
        ),
        migrations.AddField(
            model_name='team',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Est utilisé pour catégoriser les fiches. Par exemple, E/W pour les centres ayant des zones de qualification.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.teamzone', verbose_name='Zone'),
        ),
    ]
