# Generated by Django 3.2.12 on 2022-05-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_auto_20220516_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamzone',
            options={'ordering': ('short_name',), 'verbose_name': 'Zone', 'verbose_name_plural': 'Zones (Equipes)'},
        ),
    ]
