# Generated by Django 3.2.13 on 2022-06-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_alter_teamzone_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('rank', 'label'), 'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipes'},
        ),
    ]
