# Generated by Django 3.2.13 on 2022-10-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_alter_team_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyCubeRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Lien SafetyCube')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name="Etat d'avancement")),
            ],
            options={
                'verbose_name': 'Objets SafetyCube',
            },
        ),
    ]
