# Generated by Django 3.2.13 on 2022-10-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0010_safetycuberef'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownRedactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='Adresse e-mail')),
                ('fullname', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('team', models.CharField(max_length=25, verbose_name='Equipe')),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-update_date'],
                'unique_together': {('email', 'fullname', 'team')},
            },
        ),
    ]
