# Generated by Django 3.2.7 on 2021-12-06 12:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text="Afficher ou cacher ce formulaire pour l'utilisateur", verbose_name='Activé')),
                ('title', models.CharField(max_length=250, verbose_name='Titre')),
                ('slug', models.SlugField(help_text="Sera utilisé pour générer l'URL du formulaire", unique=True, verbose_name='Identifiant')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('send_email_to', models.CharField(blank=True, help_text="ou identifiant du champ contenant l'adresse de destination", max_length=250, null=True, verbose_name='Adresse e-mail de destination')),
            ],
            options={
                'verbose_name': 'Formulaire',
                'verbose_name_plural': 'Formulaires',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='SelectionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Liste de choix',
                'verbose_name_plural': 'Listes de choix',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SelectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250, verbose_name='Intitulé')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('parent_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='custom.selectionlist')),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
                'ordering': ['order', 'label'],
                'unique_together': {('label', 'parent_list')},
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(default=0, verbose_name='Rangée')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('type', models.CharField(choices=[('text-input', 'Champ Texte'), ('password', 'Champ Mot de passe'), ('checkbox', 'Case à cocher'), ('checkbox-group', 'Groupe de cases à cocher'), ('radio', 'Boutons radio'), ('select', 'Liste de sélection'), ('date', 'Champ Date'), ('time', 'Champ Heure'), ('datetime', 'Champ Date et Heure'), ('photo', 'Photo'), ('drawing', 'Schéma'), ('text', 'Texte explicatif'), ('divider', 'Séparateur'), ('empty', 'Vide')], default='text-input', max_length=100, verbose_name='Type de champ')),
                ('slug', models.SlugField(blank=True, help_text='Nom de ce champ utilisé pour le traitement des données', null=True, verbose_name='Identifiant')),
                ('required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('label', models.CharField(blank=True, max_length=250, null=True, verbose_name='Intitulé')),
                ('help_text', models.CharField(blank=True, max_length=250, null=True, verbose_name="Texte d'aide")),
                ('size', models.PositiveIntegerField(blank=True, help_text="La largeur du formulaire est divisé en 12.<br/>Saisissez ici le nombre de 12e que ce champ doit occuper.<br/>Laissez vide pour que le champ utilise tout l'espace disponible.<br/>Saississez 0 pour que le champ n'occupe que l'espace nécessaire.", null=True, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='Largeur')),
                ('attrs', models.JSONField(blank=True, default=dict, help_text='Format JSON. Seront passés à la balise HTML représentant le champ. Voir documentation pour des exemples.', null=True, verbose_name='Attributs')),
                ('choices', models.ForeignKey(blank=True, help_text="Pour les champs de type 'Liste de sélection', 'Boutons radio', 'Groupe de cases à cocher'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom.selectionlist', verbose_name='Liste de choix')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='custom.customform')),
            ],
            options={
                'verbose_name': 'Champ de formulaire',
                'verbose_name_plural': 'Champs de formulaire',
                'ordering': ['row', 'order', 'slug'],
                'unique_together': {('slug', 'form')},
            },
        ),
    ]
