# Generated by Django 3.2.12 on 2022-02-19 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('custom', '0002_auto_20220218_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='enabled',
            field=models.BooleanField(default=False, help_text="Afficher ou cacher ce formulaire pour l'utilisateur", verbose_name='Activé'),
        ),
        migrations.AlterField(
            model_name='customform',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='custom.formcategory', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='formcategory',
            name='show_to_groups',
            field=models.ManyToManyField(blank=True, default=None, help_text="Si aucun groupe n'est sélectionné, cette catégorie sera visible par tous, y compris sans authentification", related_name='related_forms', to='auth.Group', verbose_name='Montrer aux groupes'),
        ),
    ]
