# Generated by Django 3.2.12 on 2022-05-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_auto_20220520_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='help_text',
            field=models.TextField(blank=True, null=True, verbose_name="Texte d'aide"),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='type',
            field=models.CharField(choices=[('text-input', 'Champ Texte'), ('password', 'Champ Mot de passe'), ('checkbox', 'Case à cocher'), ('checkbox-group', 'Groupe de cases à cocher'), ('radio', 'Boutons radio'), ('button', 'Bouton seul'), ('button-group', 'Groupe de boutons'), ('select', 'Liste de sélection'), ('date', 'Champ Date'), ('time', 'Champ Heure'), ('datetime', 'Champ Date et Heure'), ('photo', 'Photo'), ('drawing', 'Schéma'), ('text', 'Texte explicatif'), ('alert', 'Information/Avertissement'), ('divider', 'Séparateur'), ('empty', 'Vide')], default='text-input', max_length=100, verbose_name='Type de champ'),
        ),
    ]
