# Generated by Django 3.2.13 on 2022-06-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_remove_ssoconfig__certs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssoconfig',
            name='client_uuid',
        ),
    ]
