# Generated by Django 3.2.7 on 2021-12-16 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0006_alter_userdetail_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brouillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('assigned_to_person', models.CharField(blank=True, max_length=25, null=True, verbose_name='Responsable')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'évènement")),
                ('should_notify', models.BooleanField(default=False, verbose_name='Devrait déclencher un notification')),
                ('frequency', models.CharField(max_length=100, verbose_name='Fréquence')),
                ('cwp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Position de contrôle')),
                ('description', models.TextField(verbose_name='Commentaire')),
                ('assigned_to_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brouillage', to='auth.group', verbose_name='Attribué à')),
            ],
            options={
                'verbose_name': 'Formulaire',
                'verbose_name_plural': 'Formulaires',
                'ordering': ['event_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrouillageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Catégorie')),
                ('date', models.DateField(verbose_name="Date d'enregistrement")),
                ('id_list_as_string', models.TextField(help_text='Liste des identifiants uniques de fiche séparées par des points-virgules', verbose_name='Liste des fiches')),
            ],
            options={
                'verbose_name': 'Compteur',
                'verbose_name_plural': 'Statistiques',
                'ordering': ('-date', 'category'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterferenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Intitulé')),
                ('rank', models.PositiveIntegerField(verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Type de brouillage',
                'verbose_name_plural': 'Types de brouillage',
                'ordering': ['rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sub_data', to='brouillage.brouillage', verbose_name='Fiche parente')),
            ],
            options={
                'verbose_name': 'Données sub',
            },
        ),
        migrations.CreateModel(
            name='Redactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('brouillage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redactors', to='brouillage.brouillage')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brouillage_redactors', to='shared.team')),
            ],
            options={
                'verbose_name': 'Rédacteur',
                'verbose_name_plural': 'Rédacteurs',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostIt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brouillage_postits', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postits', to='brouillage.subdata')),
            ],
            options={
                'verbose_name': 'Post-it',
                'verbose_name_plural': 'Post-its',
                'ordering': ['creation_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrouillageAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Action', max_length=250, verbose_name='Intitulé')),
                ('is_default', models.BooleanField(default=False, verbose_name='Par défaut')),
                ('is_terminal', models.BooleanField(default=False, verbose_name='Terminale')),
                ('current_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brouillage_graph_for_current_group', to='auth.group', verbose_name='Responsable actuel')),
                ('current_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brouillage_graph_for_current', to='shared.status', verbose_name='Statut actuel')),
                ('next_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brouillage_graph_for_next_group', to='auth.group', verbose_name='Prochain responsable')),
                ('next_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brouillage_graph_for_next', to='shared.status', verbose_name='Prochain statut')),
            ],
            options={
                'verbose_name': 'Action possible',
                'verbose_name_plural': "Graphe d'actions",
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='brouillage',
            name='available_actions',
            field=models.ManyToManyField(blank=True, default=None, editable=False, to='brouillage.BrouillageAction', verbose_name='Actions possibles'),
        ),
        migrations.AddField(
            model_name='brouillage',
            name='interferences',
            field=models.ManyToManyField(blank=True, default=None, to='brouillage.InterferenceType', verbose_name='Types de brouillage'),
        ),
        migrations.AddField(
            model_name='brouillage',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brouillage', to='shared.status', verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=100, verbose_name='Indicatif')),
                ('strip', models.FileField(blank=True, max_length=250, null=True, upload_to='brouillage/%Y/%m/strips/', verbose_name='Photo du strip')),
                ('fl', models.PositiveIntegerField(null=True, verbose_name='Niveau')),
                ('waypoint', models.TextField(blank=True, null=True, verbose_name='Balise')),
                ('distance', models.PositiveIntegerField(blank=True, null=True, verbose_name='Distance')),
                ('bearing', models.PositiveIntegerField(blank=True, null=True, verbose_name='Relèvement')),
                ('plaintiff', models.CharField(blank=True, choices=[('sol', 'Sol'), ('bord', 'Bord'), ('sol + bord', 'Sol + Bord')], max_length=50, null=True, verbose_name='Plaignant')),
                ('brouillage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrafts', to='brouillage.brouillage')),
            ],
            options={
                'verbose_name': 'Aéronef',
                'verbose_name_plural': 'Aéronefs',
            },
        ),
    ]
