# Generated by Django 3.2.12 on 2022-02-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brouillage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brouillage',
            name='freq_unusable',
            field=models.BooleanField(default=False, verbose_name='Fréquence inutilisable'),
        ),
        migrations.AddField(
            model_name='brouillage',
            name='supp_freq',
            field=models.BooleanField(default=False, verbose_name="Utilisation d'une fréquence supplétive"),
        ),
        migrations.AddField(
            model_name='brouillage',
            name='traffic_impact',
            field=models.BooleanField(default=False, verbose_name='Impact sur le trafic'),
        ),
    ]
